# Input/output configuration
input_dir: ${EMBEDDING_OUTPUT}
output_dir: ${FILTER_OUTPUT}
project: CodaFilteringStudy
filter_cut: 0.15

# Dataset parameters
pt_background_min: 1.
pt_signal_min: 1.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[90,5,5]] # Number of [training, validation, testing] examples
noise: False
true_edges: modulewise_true_edges


# Model parameters
n_chunks: 12
in_channels: 12
hidden: 512
nb_layer: 3
emb_channels: 0
layernorm: True
batchnorm: False
ratio: 2
weight: 1
val_subset: 0.1
warmup: 400
lr: 0.01
factor: 0.3
patience: 8
#regime: [[ci]] #[[weighting, ci]]
max_epochs: 100

# Post-processing
callbacks: [[GraphSizeMonitor, FilterTelemetry, FilterBuilder]]

