# Input/output configuration
input_dir: ${FILTER_OUTPUT}
output_dir: ${GNN_OUTPUT}
project: ${PROJECT_NAME}-gnn
edge_cut: 0.5

# Dataset parameters
pt_signal_min: 0.
pt_background_min: 0.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[9800, 100, 100]] # Number of [training, validation, testing] examples
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 0 #8
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
layernorm: True
aggregation: sum_max
hidden_activation: ReLU
weight: 2
warmup: 200
lr: 0.001
factor: 0.3
patience: 10
regime: [[]]
max_epochs: 5 #75

# Post-processing
callbacks: [[GNNModelCheckpoint, GNNTelemetry, GNNBuilder, GraphSizeMonitor]]
